[build]
  command = "echo 'no build step'"
  publish = "."

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Inclui AMBAS as árvores no pacote das funções
[functions."events"]
  included_files = ["data/events/**", "assets/data/events/**", "assets/img/banners/**"]

[functions."event"]
  included_files = ["data/events/**", "assets/data/events/**", "assets/img/banners/**"]

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "/.netlify/functions/event"
  status = 200

[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200
